services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
      - ./app/alembic.ini:/code/alembic.ini
    command: fastapi run app/main.py --host 0.0.0.0 --port 8000 --reload
