apiVersion: apps/v1
kind: Deployment
metadata:
  name: facerek-api
  namespace: facerek
spec:
  replicas: 2
  selector:
    matchLabels:
      app: facerek-api
  template:
    metadata:
      labels:
        app: facerek-api
    spec:
      containers:
        - name: facerek-api-container
          image: 774218618828.dkr.ecr.us-east-2.amazonaws.com/facerek-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: DB_PORT
            - name: COGNITO_USERPOOL_ID
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: COGNITO_USERPOOL_ID
            - name: COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: COGNITO_CLIENT_ID
            - name: COGNITO_REGION
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: COGNITO_REGION
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: S3_BUCKET_NAME
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: AWS_DEFAULT_REGION
            - name: SEND_MESSAGING
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: SEND_MESSAGING
            - name: MESSAGING_AGENT
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: MESSAGING_AGENT
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: TELEGRAM_TOKEN
            - name: TELEGRAM_USER
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: TELEGRAM_USER
            - name: TELEGRAM_GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: TELEGRAM_GROUP_ID
            - name: MATCH_FACE_CONFIDACE_TH
              valueFrom:
                secretKeyRef:
                  name: facerek-secrets
                  key: MATCH_FACE_CONFIDACE_TH
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

