name: Deploy to Amazon Lambda

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-2
  LAMBDA_FUNCTION_NAME: IdoWebsite
  
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        cd frontend
        npm ci

    - name: Build Frontend
      run: |
        cd frontend
        npm run build
        cd ..
        rm -rf ./app/public
        mv ./frontend/build ./app/public

    - name: Build Lambda Package
      run: |
        zip -r aws_lambda_artifact.zip ./app

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://aws_lambda_artifact.zip \
          --region ${{ env.AWS_REGION }}

